# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CBERSColorCorrector
                                 A QGIS plugin
 This plugin corrects the color from CBERS images to match the database
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-27
        copyright            : (C) 2023 by Mateus Sereno
        email                : mateus.sereno@ime.eb.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CBERSColorCorrector class from file CBERSColorCorrector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cbers_color_corrector import CBERSColorCorrector
    return CBERSColorCorrector(iface)
